# The name of this app. Must be unique within a project.
name: my_first_rails_app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Ruby documentation
# (https://docs.platform.sh/languages/ruby.html#supported-versions)
# to find the supported versions for the 'ruby' type.
type: "ruby:2.7"

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
  "web/uploads":
    source: local
    source_path: uploads

hooks:
  build: |
    bundle install --without development test
  deploy: |
    RACK_ENV=production bundle exec rake db:migrate

web:
  upstream:
    socket_family: "unix"
  commands:
    start: '"unicorn -l $SOCKET -E production config.ru"'
  locations:
    "/":
      root: '"public"'
      passthru: true
      expires: "1h"
      allow: true
